/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Посмотреть список всех предстоящих встреч в обогащенном формате */
        get: operations["AdminOperations_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать новый тип события с явным id */
        post: operations["AdminOperations_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Забронировать выбранный временной слот */
        post: operations["GuestOperations_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех доступных типов событий */
        get: operations["GuestOperations_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить детальную информацию о конкретном типе события */
        get: operations["GuestOperations_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить сетку слотов на 14 дней для выбранного типа события */
        get: operations["GuestOperations_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить профиль владельца календаря и его таймзону */
        get: operations["GuestOperations_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Расширенная модель бронирования для панели владельца календаря.
         *     Нужна, чтобы фронтенд мог отобразить список встреч без дополнительных запросов
         *     за названием и длительностью типа события.
         */
        AdminBooking: {
            id: string;
            eventTypeId: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            guestName: string;
            guestEmail: string;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            eventTypeTitle: string;
            /** Format: int32 */
            durationInMinutes: number;
        };
        BadRequestError: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            field?: string;
        };
        /** @description Созданное бронирование. */
        Booking: {
            id: string;
            eventTypeId: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            guestName: string;
            guestEmail: string;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
        };
        BookingRequest: {
            eventTypeId: string;
            /** Format: date-time */
            startTime: string;
            guestName: string;
            guestEmail: string;
            notes?: string;
        };
        ConflictError: {
            code: components["schemas"]["ErrorCode"];
            message: string;
        };
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "EVENT_TYPE_NOT_FOUND" | "EVENT_TYPE_ALREADY_EXISTS" | "SLOT_ALREADY_BOOKED" | "SLOT_OUTSIDE_BOOKING_WINDOW" | "SLOT_IN_PAST" | "INVALID_GUEST_EMAIL";
        /** @description Тип события для бронирования встречи. */
        EventType: {
            id: string;
            title: string;
            description: string;
            /** Format: int32 */
            durationInMinutes: number;
        };
        EventTypeCreateRequest: {
            /**
             * @description Владелец явно задает уникальный идентификатор типа события.
             *     Например: "intro-call" или "consultation-30".
             */
            id: string;
            title: string;
            description: string;
            /** Format: int32 */
            durationInMinutes: number;
        };
        /**
         * @description Подтверждение бронирования, возвращаемое гостю после успешного `POST /bookings`.
         *     Содержит название и длительность типа события, чтобы экран успеха мог
         *     отобразить полные данные без дополнительного запроса за `EventType`.
         */
        GuestBookingConfirmation: {
            id: string;
            eventTypeId: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            guestName: string;
            guestEmail: string;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            eventTypeTitle: string;
            /** Format: int32 */
            durationInMinutes: number;
        };
        NotFoundError: {
            code: components["schemas"]["ErrorCode"];
            message: string;
        };
        /**
         * @description Владелец календаря.
         *     В рамках проекта владелец один и заранее задан.
         *     Авторизация и личный кабинет не реализуются.
         */
        Owner: {
            id: string;
            name: string;
            timeZone: string;
        };
        /** @description Временной слот в календаре. */
        Slot: {
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            status: components["schemas"]["SlotStatus"];
        };
        /**
         * @description Ответ со слотами для выбранного типа события.
         *
         *     Семантика:
         *     - `slots[]` — единственный источник правды для фронта: какие слоты показывать
         *     и в каком статусе. Никаких дополнительных правил фронт не вычисляет.
         *     - Окно записи — 14 дней, начиная с текущего момента (`windowStart` … `windowEnd`).
         *     - Все времена возвращаются в UTC (`utcDateTime`); человеческое представление
         *     формируется фронтом по `Owner.timeZone`.
         *     - Статус `outside_window` означает «слот вне окна записи» (т.е. за пределами
         *     14-дневного окна). Он не описывает рабочие часы или какие-либо иные правила.
         */
        SlotListResponse: {
            eventTypeId: string;
            eventTypeTitle: string;
            /** Format: int32 */
            durationInMinutes: number;
            timeZone: string;
            /** Format: date-time */
            windowStart: string;
            /** Format: date-time */
            windowEnd: string;
            slots: components["schemas"]["Slot"][];
        };
        /** @enum {string} */
        SlotStatus: "available" | "booked" | "past" | "outside_window";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminOperations_listUpcomingBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBooking"][];
                };
            };
        };
    };
    AdminOperations_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreateRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    GuestOperations_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestBookingConfirmation"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    GuestOperations_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    GuestOperations_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    GuestOperations_listSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotListResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    GuestOperations_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
